### ISSUE TITLE
Gnome 3.16 support

### ISSUE THREAD

**Issue by varemenos** [OttoAllmendinger/gnome-shell-imgur#23]
Please add 3.16 support

**Comment by sarhugo** [comment]
It throws an error about Shell.KeyBindingMode being undefined. It's because it was renamed to Shell.ActionMode.
Modifying the line 62 of extension.js removes the error. You only need to replace Shell.KeyBindingMode.NORMAL by Shell.ActionMode.NORMAL

**Comment by OttoAllmendinger** [comment]
can you test with the current master? (run make install)

**Comment by OttoAllmendinger** [comment]
tested it, should work now
