### ISSUE TITLE
Window screenshot not working

### ISSUE THREAD

**Issue by postblue** [OttoAllmendinger/gnome-shell-imgur#26]
The title is self explanatory, and I don't know where I could find log files for this (nothing in ´lg´). Video for proof: http://media.postblue.info/u/postblue/m/imgur-screenshot-uploader/

**Comment by KateAdams** [comment]
I wonder if this has anything to do with #12.

**Comment by postblue** [comment]
I'm not a git guru, but I'll try. The revert was conflicting with later changes in `src/selection.js` so I did this: `const ScreenshotWindowIncludeFrame = true;`, and readding the workaround method. No luck.

**Comment by jacobmischka** [comment]
This also isn't working for me, and the workaround didn't seem to help either. I also can't find any logs or errors in lg.

**Comment by jacobmischka** [comment]
I found the problem. Very simple to fix but being my first time working with a gnome shell extension, very annoying to find. Lots of global logs.

**Comment by KateAdams** [comment]
@jacobmischka I can confirm here that that fix works on Gnome 3.16.2.

Thanks too.

**Comment by jacobmischka** [comment]
Just noticed this is still open, it can be closed now.

**Comment by OttoAllmendinger** [comment]
yes, thanks
