### ISSUE TITLE
Please describe what this does, exactly

### ISSUE THREAD

**Issue by mgedmin** [OttoAllmendinger/gnome-shell-imgur#30]
After reading the README I'm left with some unanswered questions: when does this extension upload screenshots to imgurl?  As soon as I hit PrintScreen, or do I get the option to choose which ones I want to share, and which ones I want to keep private?

Can you please update the README so this becomes clear?

**Comment by OttoAllmendinger** [comment]
I hope the description of the successor extension is a bit better 

https://github.com/OttoAllmendinger/gnome-shell-screenshot

;)
