### ISSUE TITLE
Copy screenshot url by default

### ISSUE THREAD

**Issue by FDiskas** [OttoAllmendinger/gnome-shell-imgur#33]
How to copy url and share? Now you need to click on notification, then wait for browser and then copy the url.
Usually this type of screenshots are made special for sharing - so copy the url by default or suggest this in notification message.

**Comment by FDiskas** [comment]
Yes I know that there is settings where can you enable it - but by default this is turned off.

**Comment by OttoAllmendinger** [comment]
Overwriting clipboard content without asking doesn't feel quite right to me. 

Are there any other extensions or apps that do that? 

I also just noticed that the "Copy Link" button inside the notification is not displayed anymore. Would that be an acceptable solution?

**Comment by FDiskas** [comment]
Yes - that's would be best solution

**Comment by Lifka** [comment]
I did it guys ;)

**Comment by OttoAllmendinger** [comment]
Successor extension https://github.com/OttoAllmendinger/gnome-shell-screenshot has a working "Copy Link" button again
