### ISSUE TITLE
Downscale images from "retina" (hidpi) display

### ISSUE THREAD

**Issue by alexanderad** [OttoAllmendinger/gnome-shell-imgur#37]
When taking a screenshot on retina desktop (which is typically scaled x2), resulting uploaded image has giant 2k width (while scaled "real displayed" is divided by scale factor).

For example, this image:
![](http://i.imgur.com/dCDu452.png)

take a look at original link: http://i.imgur.com/dCDu452.png

The solution might be an option in settings, something like "Downscale from HIDPI display", which uploads not original, but 2x down scaled image.

**Comment by OttoAllmendinger** [comment]
Migrated to https://github.com/OttoAllmendinger/gnome-shell-screenshot/issues/30
