### ISSUE TITLE
Please add setting dialog with User / Pass for my imgur account.

### ISSUE THREAD

**Issue by KingYes** [OttoAllmendinger/gnome-shell-imgur#4]
Hi !
This is very nice ext for gnome-shell.. 

I just think about good idea, to add setting dialog with User & Pass for my imgur, and all images will be upload to my account.

Can you do that?

**Comment by phaux** [comment]
:+1: for this feature

**Comment by alexanderad** [comment]
Just a side note: mac2imgur app for os x which I've used before uses login/password and oauth2 flow for getting access/refresh tokens. client secret and client id is deployed to app and present in source code: https://github.com/mileswd/mac2imgur/blob/39dfb192bd9d3a5ad470d1caf090af21f7e08b21/mac2imgur/Constants.swift#L26-L29

**Comment by Rickycezar** [comment]
👍 For this feature

**Comment by OttoAllmendinger** [comment]
Migrated to https://github.com/OttoAllmendinger/gnome-shell-screenshot/issues/31
