### ISSUE TITLE
Screenshots of selected area show selection highlighting

### ISSUE THREAD

**Issue by shgysk8zer0** [OttoAllmendinger/gnome-shell-imgur#43]
What's wrong?
Screenshots taken using "Select Area" show highlighting of selected area.
![screenshot](http://i.imgur.com/fFvRQ6U.png)

What have you tried?
-   Disabling "Keep Saved File"

Automatically detected errors:

GNOME Shell Extensions did not detect any errors with this extension.

Version information:

    Shell version: 3.22.2
    Extension version: 20

**Comment by OttoAllmendinger** [comment]
Tracked in successor project https://github.com/OttoAllmendinger/gnome-shell-screenshot/issues/28

I added a fix but it still shows up for some users.
